<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ProfileSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->women() as $i => $data) {
            $this->createUser("seed.woman.{$i}", 'Woman', 'Women', $data);
        }
        foreach ($this->men() as $i => $data) {
            $this->createUser("seed.man.{$i}", 'Man', 'Men', $data);
        }
    }

    private function women(): array
    {
        return [
            1 => [
                'name'         => 'Sarah Wanjiru',
                'nickname'     => 'Sarah',
                'age'          => 27,
                'photo_ids'    => [11, 12, 13],
                'denomination' => 'Non-denominational',
                'marital'      => 'Single',
                'body_type'    => 'Slim',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Healthcare',
                'financial'    => 'Financially stable',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Hiking', 'Coffee', 'Photography', 'Yoga', 'Cooking'],
                'bio'          => 'Nurse, worship singer, and dog mum 🐾. I believe every love story begins with prayer. Looking for a man who leads with his faith and laughs easily.',
                'email_v'      => true,
            ],
            2 => [
                'name'         => 'Esther Akinyi',
                'nickname'     => 'Esther',
                'age'          => 25,
                'photo_ids'    => [22, 23, 24],
                'denomination' => 'Pentecostal',
                'marital'      => 'Single',
                'body_type'    => 'Athletic',
                'education'    => 'Graduate Degree',
                'occupation'   => 'Finance',
                'financial'    => 'Doing well',
                'county'       => 'Kisumu',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Running', 'Fiction', 'Jazz', 'Beach', 'Cooking'],
                'bio'          => 'Finance analyst by day, avid reader by night. I run half-marathons to clear my head and cook to show love. Proverbs 31 is my north star.',
                'email_v'      => true,
            ],
            3 => [
                'name'         => 'Ruth Njeri',
                'nickname'     => 'Ruth',
                'age'          => 29,
                'photo_ids'    => [33, 34, 35],
                'denomination' => 'Anglican / Episcopal',
                'marital'      => 'Single',
                'body_type'    => 'Average',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Education',
                'financial'    => 'Financially stable',
                'county'       => 'Nakuru',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Hiking', 'Photography', 'Mountains', 'Non-Fiction', 'Art & Culture'],
                'bio'          => 'Secondary school teacher who moonlights as a weekend hiker. I have summited Longonot twice and I am saving up for Kilimanjaro. God and the outdoors keep me grounded.',
                'email_v'      => true,
            ],
            4 => [
                'name'         => 'Hannah Adhiambo',
                'nickname'     => 'Hannah',
                'age'          => 31,
                'photo_ids'    => [44, 45, 46],
                'denomination' => 'Catholic',
                'marital'      => 'Divorced',
                'body_type'    => 'Curvy',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Marketing',
                'financial'    => 'Financially stable',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => true,
                'kids'         => 1,
                'interests'    => ['Cooking', 'Wine', 'Drama', 'Fiction', 'Beach'],
                'bio'          => 'Mum to one amazing boy, marketing manager, and forever optimist. I have been through fire and come out stronger. Ready to build something beautiful with the right person.',
                'email_v'      => true,
            ],
            5 => [
                'name'         => 'Mary Wambui',
                'nickname'     => 'Mary',
                'age'          => 26,
                'photo_ids'    => [55, 56, 57],
                'denomination' => 'Baptist',
                'marital'      => 'Single',
                'body_type'    => 'Slim',
                'education'    => 'Graduate Degree',
                'occupation'   => 'Technology',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Gym', 'Pop', 'Coffee', 'Photography', 'Backpacking'],
                'bio'          => 'Software developer who loves the Word as much as I love clean code. Jeremiah 29:11 carried me through campus and I have not let it go. Gym, travel, and honest conversations are my love languages.',
                'email_v'      => true,
            ],
            6 => [
                'name'         => 'Rebecca Atieno',
                'nickname'     => 'Rebecca',
                'age'          => 28,
                'photo_ids'    => [66, 67, 68],
                'denomination' => 'Seventh-day Adventist',
                'marital'      => 'Single',
                'body_type'    => 'Fit',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Healthcare',
                'financial'    => 'Financially stable',
                'county'       => 'Mombasa',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Beach', 'Yoga', 'Cooking', 'Classical', 'Non-Fiction'],
                'bio'          => 'Pharmacist living on the coast — sea breeze and Sabbath mornings are my favourite things. Looking for someone whose faith is the foundation, not an afterthought.',
                'email_v'      => false,
            ],
            7 => [
                'name'         => 'Naomi Chebet',
                'nickname'     => 'Naomi',
                'age'          => 24,
                'photo_ids'    => [77, 78, 79],
                'denomination' => 'Charismatic',
                'marital'      => 'Single',
                'body_type'    => 'Athletic',
                'education'    => 'Some College',
                'occupation'   => 'Business',
                'financial'    => 'Just starting out',
                'county'       => 'Eldoret',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Running', 'Cycling', 'Hip-Hop', 'Adventure', 'Baking'],
                'bio'          => 'I run 10Ks before most people wake up. Raised in a strong Christian home in Eldoret and still close to my roots. Fun, focused, and unashamedly in love with Jesus.',
                'email_v'      => true,
            ],
            8 => [
                'name'         => 'Abigail Kemunto',
                'nickname'     => 'Abigail',
                'age'          => 32,
                'photo_ids'    => [88, 89, 90],
                'denomination' => 'Methodist',
                'marital'      => 'Single',
                'body_type'    => 'Average',
                'education'    => 'PhD/Doctoral',
                'occupation'   => 'Education',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Non-Fiction', 'Poetry', 'Jazz', 'Art & Culture', 'Coffee'],
                'bio'          => 'Lecturer in literature, writer on the side, and enthusiastic tea person. I believe deep conversations are a form of worship. Looking for a man who reads — anything.',
                'email_v'      => true,
            ],
            9 => [
                'name'         => 'Leah Mumbi',
                'nickname'     => 'Leah',
                'age'          => 30,
                'photo_ids'    => [1, 2, 3],
                'denomination' => 'Presbyterian',
                'marital'      => 'Divorced',
                'body_type'    => 'Curvy',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Legal',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => true,
                'kids'         => 2,
                'interests'    => ['Cooking', 'Drama', 'Romance', 'Wine', 'Beach'],
                'bio'          => 'Advocate of the High Court, mum of two incredible kids, and survivor. I cook on Sunday afternoons as a form of therapy. God turned my story around — I am excited about chapter two.',
                'email_v'      => true,
            ],
            10 => [
                'name'         => 'Priscilla Atieno',
                'nickname'     => 'Priscilla',
                'age'          => 23,
                'photo_ids'    => [4, 5, 6],
                'denomination' => 'Non-denominational',
                'marital'      => 'Single',
                'body_type'    => 'Slim',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Marketing',
                'financial'    => 'Just starting out',
                'county'       => 'Nairobi',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Pop', 'Photography', 'Coffee', 'Gym', 'Action'],
                'bio'          => 'Recent grad, content creator, and Sunday-school volunteer. I am still figuring out my twenties but I know what matters — faith, family, and good coffee.',
                'email_v'      => false,
            ],
        ];
    }

    private function men(): array
    {
        return [
            1 => [
                'name'         => 'Daniel Otieno',
                'nickname'     => 'Daniel',
                'age'          => 30,
                'photo_ids'    => [11, 12, 13],
                'denomination' => 'Pentecostal',
                'marital'      => 'Single',
                'body_type'    => 'Athletic',
                'education'    => 'Graduate Degree',
                'occupation'   => 'Engineering',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Gym', 'Rock', 'Photography', 'Hiking', 'Coffee'],
                'bio'          => 'Civil engineer who builds bridges for a living and hopes to build a family through faith. Worship team on Sundays, trail runs on Saturdays.',
                'email_v'      => true,
            ],
            2 => [
                'name'         => 'Joshua Mwangi',
                'nickname'     => 'Joshua',
                'age'          => 28,
                'photo_ids'    => [22, 23, 24],
                'denomination' => 'Anglican / Episcopal',
                'marital'      => 'Single',
                'body_type'    => 'Fit',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Finance',
                'financial'    => 'Financially stable',
                'county'       => 'Nairobi',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Cycling', 'Non-Fiction', 'Jazz', 'Cooking', 'Adventure'],
                'bio'          => 'Accountant, amateur chef, and committed churchgoer. I find peace in early-morning quiet times and good food. Not looking for perfect — looking for real.',
                'email_v'      => true,
            ],
            3 => [
                'name'         => 'Caleb Kariuki',
                'nickname'     => 'Caleb',
                'age'          => 33,
                'photo_ids'    => [33, 34, 35],
                'denomination' => 'Non-denominational',
                'marital'      => 'Divorced',
                'body_type'    => 'Average',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Business',
                'financial'    => 'Doing well',
                'county'       => 'Nakuru',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => true,
                'kids'         => 1,
                'interests'    => ['Mountains', 'Fiction', 'Drama', 'Cooking', 'Photography'],
                'bio'          => 'Entrepreneur and dad to an 8-year-old who keeps me humble every day. Divorce taught me what matters. Ready to do it right this time with the woman God has prepared.',
                'email_v'      => true,
            ],
            4 => [
                'name'         => 'Samuel Njoroge',
                'nickname'     => 'Samuel',
                'age'          => 26,
                'photo_ids'    => [44, 45, 46],
                'denomination' => 'Baptist',
                'marital'      => 'Single',
                'body_type'    => 'Muscular',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Healthcare',
                'financial'    => 'Financially stable',
                'county'       => 'Kisumu',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Gym', 'Hip-Hop', 'Beach', 'Backpacking', 'Coffee'],
                'bio'          => 'Medical officer in Kisumu. I spend my days caring for people and my evenings at the gym or by the lake. Grounded in faith, laid-back by nature.',
                'email_v'      => true,
            ],
            5 => [
                'name'         => 'Elijah Wanjiku',
                'nickname'     => 'Elijah',
                'age'          => 29,
                'photo_ids'    => [55, 56, 57],
                'denomination' => 'Catholic',
                'marital'      => 'Single',
                'body_type'    => 'Athletic',
                'education'    => 'Graduate Degree',
                'occupation'   => 'Technology',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Running', 'Classical', 'Art & Culture', 'Non-Fiction', 'Wine'],
                'bio'          => 'Product manager, daily mass attendee, marathon runner (slowly). I journal, pray, and cook — sometimes all at once. Looking for depth, not just compatibility.',
                'email_v'      => true,
            ],
            6 => [
                'name'         => 'David Achieng',
                'nickname'     => 'David',
                'age'          => 35,
                'photo_ids'    => [66, 67, 68],
                'denomination' => 'Seventh-day Adventist',
                'marital'      => 'Widowed',
                'body_type'    => 'Average',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Education',
                'financial'    => 'Financially stable',
                'county'       => 'Mombasa',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => true,
                'kids'         => 2,
                'interests'    => ['Beach', 'Cooking', 'Fiction', 'Photography', 'Yoga'],
                'bio'          => 'High school principal and widowed father of two. God has been faithful through the hardest chapter. I enjoy slow mornings, the ocean, and raising my kids to love Jesus.',
                'email_v'      => false,
            ],
            7 => [
                'name'         => 'Isaac Mutua',
                'nickname'     => 'Isaac',
                'age'          => 27,
                'photo_ids'    => [77, 78, 79],
                'denomination' => 'Charismatic',
                'marital'      => 'Single',
                'body_type'    => 'Fit',
                'education'    => 'Some College',
                'occupation'   => 'Marketing',
                'financial'    => 'Just starting out',
                'county'       => 'Nairobi',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Pop', 'Comedy', 'Coffee', 'Gym', 'Cycling'],
                'bio'          => 'Creative director for a small agency, church band keyboardist, and lover of terrible puns. I believe life is too short to be too serious.',
                'email_v'      => true,
            ],
            8 => [
                'name'         => 'Aaron Kiprop',
                'nickname'     => 'Aaron',
                'age'          => 31,
                'photo_ids'    => [88, 89, 90],
                'denomination' => 'Presbyterian',
                'marital'      => 'Single',
                'body_type'    => 'Athletic',
                'education'    => 'Graduate Degree',
                'occupation'   => 'Legal',
                'financial'    => 'Doing well',
                'county'       => 'Eldoret',
                'relocate'     => true,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Running', 'Mountains', 'Non-Fiction', 'Jazz', 'Adventure'],
                'bio'          => 'Advocate, long-distance runner, and son of a pastor. Rift Valley raised, Nairobi working. I value integrity above everything and I am ready to love intentionally.',
                'email_v'      => true,
            ],
            9 => [
                'name'         => 'Noah Onyango',
                'nickname'     => 'Noah',
                'age'          => 24,
                'photo_ids'    => [1, 2, 3],
                'denomination' => 'Methodist',
                'marital'      => 'Single',
                'body_type'    => 'Slim',
                'education'    => 'Undergraduate Degree',
                'occupation'   => 'Technology',
                'financial'    => 'Just starting out',
                'county'       => 'Nairobi',
                'relocate'     => true,
                'goal'         => 'Long-term relationship',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Sci-Fi', 'Photography', 'Rock', 'Coffee', 'Backpacking'],
                'bio'          => 'Junior dev at a fintech startup. I am that person who reads the Bible and watches sci-fi on the same Sunday afternoon. Still figuring things out, but my faith is solid.',
                'email_v'      => false,
            ],
            10 => [
                'name'         => 'Levi Wachira',
                'nickname'     => 'Levi',
                'age'          => 34,
                'photo_ids'    => [4, 5, 6],
                'denomination' => 'Non-denominational',
                'marital'      => 'Single',
                'body_type'    => 'Fit',
                'education'    => 'PhD/Doctoral',
                'occupation'   => 'Engineering',
                'financial'    => 'Doing well',
                'county'       => 'Nairobi',
                'relocate'     => false,
                'goal'         => 'Marriage',
                'has_kids'     => false,
                'kids'         => null,
                'interests'    => ['Cooking', 'Wine', 'Art & Culture', 'Non-Fiction', 'Hiking'],
                'bio'          => 'Aerospace engineer, home cook, and committed kingdom builder. I spent my twenties chasing career and I am spending my thirties chasing the things that last.',
                'email_v'      => true,
            ],
        ];
    }

    private function createUser(string $emailPrefix, string $gender, string $showMe, array $d): void
    {
        $email = "{$emailPrefix}@kingdomdating.test";

        $user = User::firstOrCreate(
            ['email' => $email],
            ['name' => $d['name'], 'password' => Hash::make('password')],
        );

        $birthDate = Carbon::today()->subYears($d['age'])->subDays(rand(0, 180));
        $index = (int) filter_var($emailPrefix, FILTER_SANITIZE_NUMBER_INT);

        $profile = $user->profile()->updateOrCreate(
            ['user_id' => $user->id],
            [
                'nickname'         => $d['nickname'],
                'birth_date'       => $birthDate,
                'gender'           => $gender,
                'marital_status'   => $d['marital'],
                'body_type'        => $d['body_type'],
                'bio'              => $d['bio'],
                'kingdom_purpose'  => 'Dating',
                'relationship_goal'=> $d['goal'],
                'is_believer'      => true,
                'denomination'     => $d['denomination'],
                'has_kids'         => $d['has_kids'],
                'kids_count'       => $d['kids'],
                'education_level'  => $d['education'],
                'occupation'       => $d['occupation'],
                'financial_status' => $d['financial'],
                'country'          => 'Kenya',
                'county_state'     => $d['county'],
                'willing_to_relocate' => $d['relocate'],
                'interests'        => $d['interests'],
                'show_me'          => $showMe,
                'age_min'          => 22,
                'age_max'          => 45,
                'admin_contact_consent' => false,
                'email_verified'   => $d['email_v'],
                'phone_verified'   => false,
                'completed_step'   => 5,
            ],
        );

        $photoFolder = strtolower($gender) === 'man' ? 'men' : 'women';
        $profile->photos()->delete();
        foreach ($d['photo_ids'] as $position => $photoId) {
            $profile->photos()->create([
                'position' => $position,
                'path'     => "https://randomuser.me/api/portraits/{$photoFolder}/{$photoId}.jpg",
                'is_main'  => $position === 0,
            ]);
        }
    }
}
